EXAMPLE = {
    "searchModel": {
        "keyword": "9780373125296",
        "page": 0,
        "pagination": 1,
        "size": 10,
        "sortType": "default",
        "sortOrder": "asc",
        "modifiers": {},
        "expedite": "",
    },
    "products": [
        {
            "eanCode": "9780373125296",
            "loyaltyAccrual": {
                "pointsMultiplier": 1,
                "pointsAdditional": 0,
                "promoDescription": "",
            },
            "itemPrimaryName": "The Italian Duke's Wife",
            "itemSecondaryName": "",
            "itemSeriesName": "",
            "contributor": [
                {"contributorRole": "Author", "contributorName": "Penny Jordan"}
            ],
            "publishDate": "2006-03-28",
            "itemProducerPrimary": "Harlequin Presents",
            "itemProducerSecondary": "Harlequin Presents",
            "itemNameEdition": "Original ed.",
            "languageString": "",
            "producerCountry": "Canada",
            "itemProducerPlace": "",
            "descripShort": "",
            "descripLong": "",
            "formatCode": "BC",
            "formatText": "Paperback",
            "websiteCategory": "0000000001",
            "bicCodes": [{"bicCode": "FRD", "bicDesc": "Adult & contemporary romance"}],
            "itemContentDescription": "",
            "itemIllustrations": "",
            "itemPages": "187",
            "itemRunTime": "",
            "itemFileSize": "",
            "interestAge": "",
            "readingAge": "",
            "replacesEan": "",
            "alternateEan": "",
            "alternateEbookEan": "",
            "replacedByEan": "",
            "productTags": [],
            "axFormatCode": "PB",
            "axFormatText": "PAPERBACK",
            "firstListContributor": "Author : Penny Jordan",
            "itemWeight": "95",
            "itemHeight": "169",
            "itemWidth": "108",
            "itemSpine": "13",
            "itemPrizes": "",
            "discounts": [[]],
            "bestAvailability": {
                "eanCode": "9780795708855",
                "vendorCode": "wf01",
                "websitePrice": 328,
                "availabilityCode": "96",
                "leadTimeDays": "3",
                "leadTimeHours": "72",
                "leadTimeDescription": "Approx. 72 Working Hours",
                "stockQty": "2",
                "availabilityFlag": "Y",
                "dispatchDate": "2020-05-27",
                "expedite": False,
                "saleStock": False,
            },
            "fallBackAvailability": {
                "eanCode": "9780795708855",
                "vendorCode": "OBNB02",
                "websitePrice": 304,
                "availabilityCode": "72",
                "leadTimeDays": "9",
                "leadTimeHours": "219",
                "leadTimeDescription": "Approx. 5 - 9 Working Days",
                "stockQty": "10",
                "availabilityFlag": "Y",
                "dispatchDate": "2020-06-04",
                "expedite": False,
            },
            "rating": {
                "related_item_id": "9780373125296",
                "totalRatings": 0,
                "rating": 0,
            },
        }
    ],
    "pagination": {"total": 1, "size": "0"},
    "navigations": [],
    "suggestions": None,
}
